### ISSUE TITLE
sentry hanging

### ISSUE THREAD

**Issue by artooro** [rferreira/sentry#2]
I'm having trouble with sentry hanging up on me. It will run for awhile, but will stop responding to all DNS requests.

The process only uses 0.1% CPU running at 4 threads. And I'm able to exit sentry normally, it just stops responding to all requests.

Anyone else come across this? Or do I need to look for some other source code to work off of.

**Comment by rferreira** [comment]
Ill take a look at it to tonight.

**Comment by rferreira** [comment]
I believe I fixed the bug you were running into, can you check the latest code from the master branch? There are still a couple concurrency edge cases that I need to fix before the next release. Should happen in the next few days.

**Comment by artooro** [comment]
Thanks, you rock! I'll check it out and get back to you here, might be tomorrow.

**Comment by rferreira** [comment]
My pleasure.

**Comment by rferreira** [comment]
fixed in version 0.5
